"""add_secret_phrase_to_user

Revision ID: 8960007f71a5
Revises: e7831c21ffa4
Create Date: 2026-05-21 14:40:28.663533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8960007f71a5'
down_revision: Union[str, None] = 'e7831c21ffa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_phrase', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_phrase')
    # ### end Alembic commands ###
