"""Add GlobalAdmin table

Revision ID: a8b9051e66c3
Revises: 5579e2a55291
Create Date: 2026-04-27 16:22:00.214286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b9051e66c3'
down_revision: Union[str, None] = '5579e2a55291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_admins_email'), 'global_admins', ['email'], unique=True)
    op.create_index(op.f('ix_global_admins_id'), 'global_admins', ['id'], unique=False)
    op.alter_column('call_status_history', 'status',
               existing_type=postgresql.ENUM('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus'),
               type_=sa.Enum('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('emergency_calls', 'status',
               existing_type=postgresql.ENUM('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus'),
               type_=sa.Enum('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('emergency_calls', 'status',
               existing_type=sa.Enum('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus', native_enum=False),
               type_=postgresql.ENUM('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus'),
               existing_nullable=True)
    op.alter_column('call_status_history', 'status',
               existing_type=sa.Enum('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus', native_enum=False),
               type_=postgresql.ENUM('created', 'searching', 'offer_sent', 'accepted', 'en_route', 'arrived', 'completed', 'cancelled_by_user', 'cancelled_by_system', name='callstatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_global_admins_id'), table_name='global_admins')
    op.drop_index(op.f('ix_global_admins_email'), table_name='global_admins')
    op.drop_table('global_admins')
    # ### end Alembic commands ###
