"""add_is_new_to_user

Revision ID: e7831c21ffa4
Revises: a8b9051e66c3
Create Date: 2026-05-21 14:13:54.069516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7831c21ffa4'
down_revision: Union[str, None] = 'a8b9051e66c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_new = false")
    op.alter_column('users', 'is_new', nullable=False, server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_new')
    # ### end Alembic commands ###
